name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov   # Explicitly install test dependencies
    
    - name: List installed packages
      run: pip list
    
    - name: Run basic test
      run: |
        python -m pytest tests/test_github_actions.py -v
    
    - name: Run unit tests
      run: |
        python -m pytest -m unit -v   # Use python -m to ensure correct import paths
    
    - name: Run integration tests
      run: |
        python -m pytest -m integration -v
    
    - name: Generate coverage report
      run: |
        python -m pytest --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
